### PR TITLE
Feature/class

### PR DESCRIPTION
**Pull request by ivyleavedtoadflax**
Hi @davidsbatista I've now created a class in which the logic can sit. I now plan to copy this to a new [repo](https://github.com/ivyleavedtoadflax/nervaluate) where I can turn it into a package, but just wanted to give you a heads up on what changes I have made so far.

One new feature is that I have added the ability to subset the tags of interest, so in `compute_metrics` you can specify a list of tags that you want to evaluate for. The result of this is that if I was to set the list to `['PER', 'LOC']` but in the predicted tags there is `['PER', 'LOC', 'MISC']` any `MISC` tags would immediately be classed as spurious (or partial, etc. if there was an overlap). In fact this case already existed if a model predicted a class that was not in the evaluation set, so it's not really a new issue.

The other by-product of this is that when it evaluates the metrics at the token level, it is not clear where to assign a spurious tag. For instance:

```
predicted = ['O', 'O', 'B-PER', 'L-PER', 'O', 'B-FOO', 'L-FOO', 'O', 'B-LOC', 'L-LOC']
true = ['O', 'O', 'B-PER', 'L-PER', 'O', 'O', 'O', 'O', 'B-LOC', 'L-LOC']
```
It is clear in this case that the overall score would be:

```
{'ent_type': {'correct': 2,
  'incorrect': 0,
  'partial': 0,
  'missed': 0,
  'spurious': 1,
  'possible': 2,
  'actual': 3},
 'partial': {'correct': 2,
  'incorrect': 0,
  'partial': 0,
  'missed': 0,
  'spurious': 1,
  'possible': 2,
  'actual': 3},
 'strict': {'correct': 2,
  'incorrect': 0,
  'partial': 0,
  'missed': 0,
  'spurious': 1,
  'possible': 2,
  'actual': 3},
 'exact': {'correct': 2,
  'incorrect': 0,
  'partial': 0,
  'missed': 0,
  'spurious': 1,
  'possible': 2,
  'actual': 3}}
```
However it's less clear what the tag level scores should be. As mentioned, I have defaulted to adding spurious tokens to each of the tag level scores, so it will look like:

```
{'PER': {'ent_type': {'correct': 1,
   'incorrect': 0,
   'partial': 0,
   'missed': 0,
   'spurious': 1,
   'possible': 1,
   'actual': 2},
  'partial': {'correct': 1,
   'incorrect': 0,
   'partial': 0,
   'missed': 0,
   'spurious': 1,
   'possible': 1,
   'actual': 2},
  'strict': {'correct': 1,
   'incorrect': 0,
   'partial': 0,
   'missed': 0,
   'spurious': 1,
   'possible': 1,
   'actual': 2},
  'exact': {'correct': 1,
   'incorrect': 0,
   'partial': 0,
   'missed': 0,
   'spurious': 1,
   'possible': 1,
   'actual': 2}},
 'LOC': {'ent_type': {'correct': 1,
   'incorrect': 0,
   'partial': 0,
   'missed': 0,
   'spurious': 1,
   'possible': 1,
   'actual': 2},
  'partial': {'correct': 1,
   'incorrect': 0,
   'partial': 0,
   'missed': 0,
   'spurious': 1,
   'possible': 1,
   'actual': 2},
  'strict': {'correct': 1,
   'incorrect': 0,
   'partial': 0,
   'missed': 0,
   'spurious': 1,
   'possible': 1,
   'actual': 2},
  'exact': {'correct': 1,
   'incorrect': 0,
   'partial': 0,
   'missed': 0,
   'spurious': 1,
   'possible': 1,
   'actual': 2}}}
```

Let me know if you think this makes sense.

### CODE REVIEW

**Comment by ivyleavedtoadflax** [comment]
Just thinking about this, perhaps this is not right in the tag level case - should the spurious cases be recorded under `'FOO'`?

**Comment by davidsbatista** [comment]
Regarding the new feature, having a another list as input with tags to ignore (i.e., or computing this list from all the tags minus to ones to evaluate) and every time the gold standard or the prediction contains that tag we ignore it, skip it, would that work? Otherwise, for the time being I would just evaluate on everything.

Another thing that crossed my mind is to have a function that accepts as input the CoNLL format, or simple a file with two entry (true and predicted) per line separated by a tab character; it's a very common format for output of sequence labelling tasks; this would make the use of the package as simple as running from the shell giving as input a file with the (true, predictions) pair.

**Comment by ivyleavedtoadflax** [comment]
Yes that makes sense, create a list of all tags either predicted or gold,
then ignore any who are not in the passed list. Incidentally my main
motivation for this functionality was because I'm often evaluating generic
models where a subset of tags are no use whatsoever, and I don't have gold
data to evaluate them, so I want to exclude them from the overall metrics.

Agree on CoNLL format. I'd also like to add functionality for spaCy format.
Ideally it would accept a single or two files of gold and predictions, and
work from that.

**Comment by davidsbatista** [comment]
OK, I would say than I merge this one when the functionality is fixed to ignore any tag which is not in the passed list.

Then I would say, let's spec the functionalities we want, e.g.: read CoNLL format, integrate with spaCy, also have some complete/structured JSON report with the default per-tag evaluation as well, just for the sake of completeness.

What do you say?

**Comment by ivyleavedtoadflax** [comment]
Sounds good. I'll need to focus on the functionality I need for work, but happy to split the tasks along those lines :+1:

**Comment by ivyleavedtoadflax** [comment]
Hoping to have a bit of time to get back to this soon!

**Comment by davidsbatista** [comment]
Hey Matt, no worries, take your time, I'm also with a bit of too much on my plate right now, but happy to take this one with you and make a nice python package to NER evaluation.

**Comment by ivyleavedtoadflax** [comment]
Took me a long time to get my head back into it, but have made some progress.

So I've renamed the labels argument in the `Evaluator` class to `tags` to be more consistent with the rest of the code. It is not used to subset both the predicted named entities and the true named entities. The results are enshrined in the tests. This solves the two situations I was encountering:

* When a model has not been trained to predict a particular tag, but it is present in the true data.
* When the model predicts a particular tag, but it is not present in the true data.

You will need to specify which tags you are interested in each time you instantiate the `Evaluator` class, but actually this is no different from the current situation when calling the `compute_metrics` function. 

The behaviour is enshrined in the tests:

* test_evaluator_simple_case_filtered_tags
* test_compute_metrics_extra_tags_in_prediction

**Comment by ivyleavedtoadflax** [comment]
@davidsbatista is this good to merge?

**Comment by davidsbatista** [comment]
Hey @ivyleavedtoadflax, sorry I kind of forgot about it, looks OK. I couldn't see if you updated the notebook with the example or not, if you didn't can you updated it when you have time? Otherwise looks fine, going to merge it.

**Comment by ivyleavedtoadflax** [comment]
Ah yes, not sure anything will change in the notebook, but I will have a
look.

**Pull request merged**
